"""adiciona tabela indicacao

Revision ID: 0f542ad9399c
Revises: bbedf8e37a41
Create Date: 2026-05-16 00:15:03.026843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f542ad9399c'
down_revision = 'bbedf8e37a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'CANCELADA', 'REJEITADA', name='status_indicacao_enum'), nullable=False),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('data_rejeicao', sa.DateTime(), nullable=True),
    sa.Column('tem_climatizacao', sa.Boolean(), nullable=False),
    sa.Column('tem_monitores', sa.Boolean(), nullable=False),
    sa.Column('tem_gratuidade', sa.Boolean(), nullable=False),
    sa.Column('porte', sa.Enum('PEQUENO', 'MEDIO', 'GRANDE', name='porte_indicacao_enum'), nullable=False),
    sa.Column('usuario_indicador_id', sa.Integer(), nullable=False),
    sa.Column('usuario_analisador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_analisador_id'], ['usuario.id'], name='fk_indicacao_usuario_analisador'),
    sa.ForeignKeyConstraint(['usuario_indicador_id'], ['usuario.id'], name='fk_indicacao_usuario_indicador'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicacao')
    # ### end Alembic commands ###
