"""adiciona tabela brinquedoteca

Revision ID: 91193ec7719f
Revises: 0f542ad9399c
Create Date: 2026-05-16 20:05:41.586159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91193ec7719f'
down_revision = '0f542ad9399c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brinquedoteca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='status_brinquedoteca_enum'), nullable=False),
    sa.Column('indicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicacao_id'], ['indicacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brinquedoteca')
    # ### end Alembic commands ###
