"""migracao geral atualizada

Revision ID: bc3561bdbd96
Revises: 879c478d60f1
Create Date: 2026-05-19 22:11:31.555267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3561bdbd96'
down_revision = '879c478d60f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=False),
    sa.Column('brinquedoteca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_avaliador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brinquedoteca_id'], ['brinquedoteca.id'], ),
    sa.ForeignKeyConstraint(['usuario_avaliador_id'], ['usuario.id'], name='fk_avaliacao_usuario_avaliador'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_avaliador_id', 'brinquedoteca_id', name='uq_usuario_brinquedoteca_avaliacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
