"""migracao geral atualizada

Revision ID: ce5978b9ba0e
Revises: 
Create Date: 2026-05-19 23:10:34.135219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5978b9ba0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('CIDADAO', 'ADMIN', name='perfil_usuario_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('indicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'CANCELADA', 'REJEITADA', name='status_indicacao_enum'), nullable=False),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('data_rejeicao', sa.DateTime(), nullable=True),
    sa.Column('tem_climatizacao', sa.Boolean(), nullable=False),
    sa.Column('tem_monitores', sa.Boolean(), nullable=False),
    sa.Column('tem_gratuidade', sa.Boolean(), nullable=False),
    sa.Column('porte', sa.Enum('PEQUENO', 'MEDIO', 'GRANDE', name='porte_indicacao_enum'), nullable=False),
    sa.Column('usuario_indicador_id', sa.Integer(), nullable=False),
    sa.Column('usuario_analisador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_analisador_id'], ['usuario.id'], name='fk_indicacao_usuario_analisador'),
    sa.ForeignKeyConstraint(['usuario_indicador_id'], ['usuario.id'], name='fk_indicacao_usuario_indicador'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brinquedoteca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='status_brinquedoteca_enum'), nullable=False),
    sa.Column('indicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicacao_id'], ['indicacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicacao_id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('indicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicacao_id'], ['indicacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicacao_id')
    )
    op.create_table('fotografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('indicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicacao_id'], ['indicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=False),
    sa.Column('brinquedoteca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_avaliador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brinquedoteca_id'], ['brinquedoteca.id'], ),
    sa.ForeignKeyConstraint(['usuario_avaliador_id'], ['usuario.id'], name='fk_avaliacao_usuario_avaliador'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_avaliador_id', 'brinquedoteca_id', name='uq_usuario_brinquedoteca_avaliacao')
    )
    op.create_table('localizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endereco_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localizacao')
    op.drop_table('avaliacao')
    op.drop_table('fotografia')
    op.drop_table('endereco')
    op.drop_table('brinquedoteca')
    op.drop_table('indicacao')
    op.drop_table('usuario')
    # ### end Alembic commands ###
